---
markets: "" # comma-separated list of 2-letters country codes. empty for all
availability: "" # comma-separated list of any: enabled, referral, invite, request, deprecated, soon
provider: "A3C2" # the middle bit in the class name for the gateway - Integrations::THIS_HERE::Gateway
processor: "Base" # the expected list of functions to support, one of Acounting, Website, Email, Data, Payment or Shipment 
logo: "https://res.cloudinary.com/subscribility-p/image/upload/w_128/cdn/qr.a3c2.com/logo.png" #link to logo image. displaied as 80x80 and 120x120
hero: "" #link to hero image.
website: "" 
info_url: "" # link to website where more product information can be found
support_url: ""
pricing_url: "" # link to website where more product information can be found
pricing: ""
tags: "third-party"
supports: "products_updown,customers_down"
tbyb: true

production:
  admin_url: "" # link to admin panel, allow for premium partners to have direct nav access

development:

test:

layout:
  fields: "_select_your_plan,plan_selected,_qr_config,qr_code_eye,qr_code_ball,qr_code_style,colour_text,colour_bg,colour_eye,colour_ball"

  _select_your_plan:
    type: "section"

  plan_selected:
    size: "col-12"
    type: "radio"
    validate: "required,in-list"
    options: "qr_codes|basic_labels|advanced_labels"

  _qr_config:
    type: "section"

  qr_code_style:
    size: "col-12"
    type: "select-image"
    validate: "required,in-list"
    options: "square=https://www.qrcode-monkey.com/img/qr/body/square.png&dot=https://www.qrcode-monkey.com/img/qr/body/dot.png&round=https://www.qrcode-monkey.com/img/qr/body/round.png&circle=https://www.qrcode-monkey.com/img/qr/body/circle.png&circle-zebra=https://www.qrcode-monkey.com/img/qr/body/circle-zebra.png&circle-zebra-vertical=https://www.qrcode-monkey.com/img/qr/body/circle-zebra-vertical.png&circular=https://www.qrcode-monkey.com/img/qr/body/circular.png"
  
  qr_code_eye:
    size: "col-12"
    type: "select-image"
    validate: "required,in-list"
    options: "frame0=https://www.qrcode-monkey.com/img/qr/eye-frames/frame0.png&frame1=https://www.qrcode-monkey.com/img/qr/eye-frames/frame1.png&frame2=https://www.qrcode-monkey.com/img/qr/eye-frames/frame2.png&frame3=https://www.qrcode-monkey.com/img/qr/eye-frames/frame3.png&frame12=https://www.qrcode-monkey.com/img/qr/eye-frames/frame12.png&frame13=https://www.qrcode-monkey.com/img/qr/eye-frames/frame13.png&frame5=https://www.qrcode-monkey.com/img/qr/eye-frames/frame5.png"

  qr_code_ball:
    size: "col-12"
    type: "select-image"
    validate: "required,in-list"
    options: "ball0=https://www.qrcode-monkey.com/img/qr/eye-balls/ball0.png&ball1=https://www.qrcode-monkey.com/img/qr/eye-balls/ball1.png&ball2=https://www.qrcode-monkey.com/img/qr/eye-balls/ball2.png&ball3=https://www.qrcode-monkey.com/img/qr/eye-balls/ball3.png&ball14=https://www.qrcode-monkey.com/img/qr/eye-balls/ball14.png&ball15=https://www.qrcode-monkey.com/img/qr/eye-balls/ball15.png&ball11=https://www.qrcode-monkey.com/img/qr/eye-balls/ball11.png"

  fore_colour_start:
    size: "col-6"
    type: "color"
  
  eye_outside_colour:
    size: "col-6"
    type: "color"

  eye_inside_colour:
    size: "col-6"
    type: "color"

translations:
  en:
    name: "QR Codes, Product & Nutrition eLabels"
    info: "Provide customers with the best product experience post-purchase, including accurate information about a product and most importantly the people involved in bringing it to life."
    description: "Provide customers with the best product experience post-purchase, including accurate information about a product and most importantly the people involved in bringing it to life.\nThis application generates configurable and tracable QR codes, for each product, allowing customers to access full product information and provide feedback.\n<img width=110 height=110 style=\"margin-left:10%;\" src=\"https://a3c2.com/images/sample-all.gif\">"
    benefits: "configure look-and-feel for all QR codes generated\ngenerate eLabels with offers, subscriptions or time-limited offers\nadd regulatory details such as nutrition information for each product"
    instructions: "You do not require an account to continue. Troly will create one for you. QR codes will be generated for your entire product catalogue within a few minutes of having configured the application."
    support: ""
    price: "19"
    price_max: "89"
    pricing: "This application offers 3 packages and levels of functionality. All Troly customers instantly get a 20% discount on all plans offered by ACME QR Codes."
    premium: ""
    ondemand: "QR Codes are generated once and regenerated on-demand."
    ondemand_options: "create_qrcode_products=Generate All Products QR Codes&create_qrcode_product=Generate Product QR Codes&create_qrcode_customers=Generate All Contacts QR Codes&create_qrcode_customer=Generate Contact QR Codes"

    plans_details:
      qr_codes:
        price: 19
        description: "QR Codes"
      basic_labels:
        price: 49
        description: "QR Codes + eLabels"
      advanced_labels:
        price: 89
        description: "QR Codes + eLabels + Nutrition details"

    labels:
      _select_your_plan:
        label: "Select the plan that suits you best"
        hint: "To continue using this application you must select a plan."
      
      plan_selected:
        label: "Plan Selected (-20% off!)"
        options: "qr_codes=Unlimited QR Codes only ($19)&basic_labels=Unlimited QR Codes and product eLabels ($49)&advanced_labels=Unlimited QR codes, eLabels, and Nutrition Information labels ($89)"
        hint: "All functionality is available immediately, however downgrading will also result in immediate data loss."

      _qr_config:
        label: "Configure your QR codes"
      
      qr_code_style:
        label: "QR Style"

      qr_code_eye:
        label: "Eye Outer Style"
      
      qr_code_ball:
        label: "Eye Inner Style"

      fore_colour_start:
        label: "Code Color"
      
      eye_outside_colour:
        label: "Outer Eye Color"
      
      eye_inside_colour:
        label: "Inner Eye Color"