baseurl: /
url: https://a3c2.com/

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: A3C2 Project
full_title: The A3C2 Project
show_downloads: false
description: QR Codes, Product Information and Nutrition Labels for businesses who value customer relationships.

logo: https://res.cloudinary.com/subscribility-p/image/upload/w_250/cdn/qr.a3c2.com/logo.png

github:
  is_project_page: false
  show_hosted: false